sudo: false

language: python

env:
    -
    - INSTALL_CONFIGOBJ=x

install:
    - pip install proselint pyyaml
    - if [ -v INSTALL_CONFIGOBJ ]; then pip install configobj; fi

python:
    - "2.7"
    - "3.4"
    - "3.5"

script:
    - ./test/test.bash
